apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: lol-tracker
  labels:
    app: lol-backend
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "lol_tracker"
  DB_USER: "postgres"
  REDIS_URL: "redis:6379"
  GIN_MODE: "release"
  OTEL_ENDPOINT: "jaeger:4318"
  OTEL_SERVICE_NAME: "lol-match-tracker-api"
