FROM golang:1.25

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Copy source code
COPY . .

# Build WITHOUT optimisations so breakpoints and variables work correctly
RUN go build -gcflags="all=-N -l" -o main cmd/server/main.go

# 8080 = app, 2345 = Delve
EXPOSE 8080 2345

# Delve wraps the binary and waits for VS Code to attach before running it
CMD ["/go/bin/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./main"]
