apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lol-backend.fullname" . }}-secret
  labels:
    {{- include "lol-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | required "secrets.DB_PASSWORD is required" | quote }}
  RIOT_API_KEY: {{ .Values.secrets.RIOT_API_KEY | required "secrets.RIOT_API_KEY is required" | quote }}
